//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8670
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System;
using System.Collections;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class trigger_system
{

    private trigger_systemEvent_tracksEvent_track[] event_tracksField;

    private trigger_systemTriggersTrigger[] triggersField;

    private string typeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("event_track", typeof(trigger_systemEvent_tracksEvent_track), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public trigger_systemEvent_tracksEvent_track[] event_tracks
    {
        get
        {
            return this.event_tracksField;
        }
        set
        {
            this.event_tracksField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("trigger", typeof(trigger_systemTriggersTrigger), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public trigger_systemTriggersTrigger[] triggers
    {
        get
        {
            return this.triggersField;
        }
        set
        {
            this.triggersField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class trigger_systemEvent_tracksEvent_track
{

    private trigger_systemEvent_tracksEvent_trackTrack[] trackField;

    private string ecField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("track", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public trigger_systemEvent_tracksEvent_trackTrack[] track
    {
        get
        {
            return this.trackField;
        }
        set
        {
            this.trackField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ec
    {
        get
        {
            return this.ecField;
        }
        set
        {
            this.ecField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class trigger_systemEvent_tracksEvent_trackTrack
{

    private string idField;

    private string nameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class trigger_systemTriggersTrigger : IComparable 
{

    private string typeField;

    private string idField;

    private string timeField;

    private string durationField;

    private string repeatField;

    private string ecField;

    private string trackField;

    private string eventField;

    private string boneField;

    private string tierField;

    private string refidField;

    private string speedField;

    private string tangentxField;

    private string tangentyField;

    private string tangentzField;

    private string actionField;

    public int CompareTo(object obj)
    {
        trigger_systemTriggersTrigger otherTrigger = obj as trigger_systemTriggersTrigger;
        if (otherTrigger != null)
        {
            if (this.ec != otherTrigger.ec)
            {
               return this.ec.CompareTo(otherTrigger.ec);
            }
            else if (this.track != otherTrigger.track)
            {
                return this.track.CompareTo(otherTrigger.track);
            } else
            {
                return this.id.CompareTo(otherTrigger.id);
            }
        }
        else {
            throw new ArgumentException("Object is not a trigger_systemTriggersTrigger");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string time
    {
        get
        {
            return this.timeField;
        }
        set
        {
            this.timeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string duration
    {
        get
        {
            return this.durationField;
        }
        set
        {
            this.durationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string repeat
    {
        get
        {
            return this.repeatField;
        }
        set
        {
            this.repeatField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ec
    {
        get
        {
            return this.ecField;
        }
        set
        {
            this.ecField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string track
    {
        get
        {
            return this.trackField;
        }
        set
        {
            this.trackField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @event
    {
        get
        {
            return this.eventField;
        }
        set
        {
            this.eventField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string bone
    {
        get
        {
            return this.boneField;
        }
        set
        {
            this.boneField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tier
    {
        get
        {
            return this.tierField;
        }
        set
        {
            this.tierField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string refid
    {
        get
        {
            return this.refidField;
        }
        set
        {
            this.refidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string speed
    {
        get
        {
            return this.speedField;
        }
        set
        {
            this.speedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("tangent.x")]
    public string tangentx
    {
        get
        {
            return this.tangentxField;
        }
        set
        {
            this.tangentxField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("tangent.y")]
    public string tangenty
    {
        get
        {
            return this.tangentyField;
        }
        set
        {
            this.tangentyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("tangent.z")]
    public string tangentz
    {
        get
        {
            return this.tangentzField;
        }
        set
        {
            this.tangentzField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string action
    {
        get
        {
            return this.actionField;
        }
        set
        {
            this.actionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class NewDataSet
{

    private trigger_system[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("trigger_system")]
    public trigger_system[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}
