//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8670
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class VisEffectArtInfos {
    
    private VisEffectArtInfosVisEffectArtInfo[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("VisEffectArtInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public VisEffectArtInfosVisEffectArtInfo[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class VisEffectArtInfosVisEffectArtInfo {
    
    private string nameField;
    
    private string fOWMaskField;
    
    private string fBaseDurationField;
    
    private string fBaseDurationScaleField;
    
    private string fMovementSpeedField;
    
    private VisEffectArtInfosVisEffectArtInfoTransform[] transformField;
    
    private VisEffectArtInfosVisEffectArtInfoSoundEffectsSoundEffect[] soundEffectsField;
    
    private VisEffectArtInfosVisEffectArtInfoModelEffectsModelEffect[] modelEffectsField;
    
    private VisEffectArtInfosVisEffectArtInfoParticleEffectsParticleEffect[] particleEffectsField;
    
    private VisEffectArtInfosVisEffectArtInfoChildEffectsChildEffect[] childEffectsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FOWMask {
        get {
            return this.fOWMaskField;
        }
        set {
            this.fOWMaskField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string fBaseDuration {
        get {
            return this.fBaseDurationField;
        }
        set {
            this.fBaseDurationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string fBaseDurationScale {
        get {
            return this.fBaseDurationScaleField;
        }
        set {
            this.fBaseDurationScaleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string fMovementSpeed {
        get {
            return this.fMovementSpeedField;
        }
        set {
            this.fMovementSpeedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Transform", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public VisEffectArtInfosVisEffectArtInfoTransform[] Transform {
        get {
            return this.transformField;
        }
        set {
            this.transformField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("SoundEffect", typeof(VisEffectArtInfosVisEffectArtInfoSoundEffectsSoundEffect), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public VisEffectArtInfosVisEffectArtInfoSoundEffectsSoundEffect[] SoundEffects {
        get {
            return this.soundEffectsField;
        }
        set {
            this.soundEffectsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ModelEffect", typeof(VisEffectArtInfosVisEffectArtInfoModelEffectsModelEffect), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public VisEffectArtInfosVisEffectArtInfoModelEffectsModelEffect[] ModelEffects {
        get {
            return this.modelEffectsField;
        }
        set {
            this.modelEffectsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ParticleEffect", typeof(VisEffectArtInfosVisEffectArtInfoParticleEffectsParticleEffect), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public VisEffectArtInfosVisEffectArtInfoParticleEffectsParticleEffect[] ParticleEffects {
        get {
            return this.particleEffectsField;
        }
        set {
            this.particleEffectsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ChildEffect", typeof(VisEffectArtInfosVisEffectArtInfoChildEffectsChildEffect), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public VisEffectArtInfosVisEffectArtInfoChildEffectsChildEffect[] ChildEffects {
        get {
            return this.childEffectsField;
        }
        set {
            this.childEffectsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class VisEffectArtInfosVisEffectArtInfoTransform {
    
    private string scaleField;
    
    private VisEffectArtInfosVisEffectArtInfoTransformTranslation[] translationField;
    
    private VisEffectArtInfosVisEffectArtInfoTransformRotation[] rotationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Scale {
        get {
            return this.scaleField;
        }
        set {
            this.scaleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Translation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public VisEffectArtInfosVisEffectArtInfoTransformTranslation[] Translation {
        get {
            return this.translationField;
        }
        set {
            this.translationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Rotation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public VisEffectArtInfosVisEffectArtInfoTransformRotation[] Rotation {
        get {
            return this.rotationField;
        }
        set {
            this.rotationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class VisEffectArtInfosVisEffectArtInfoTransformTranslation {
    
    private string xField;
    
    private string yField;
    
    private string zField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string z {
        get {
            return this.zField;
        }
        set {
            this.zField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class VisEffectArtInfosVisEffectArtInfoTransformRotation {
    
    private string xField;
    
    private string yField;
    
    private string zField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string z {
        get {
            return this.zField;
        }
        set {
            this.zField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class VisEffectArtInfosVisEffectArtInfoSoundEffectsSoundEffect {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class VisEffectArtInfosVisEffectArtInfoModelEffectsModelEffect {
    
    private string nameField;
    
    private string animationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Animation {
        get {
            return this.animationField;
        }
        set {
            this.animationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class VisEffectArtInfosVisEffectArtInfoParticleEffectsParticleEffect {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class VisEffectArtInfosVisEffectArtInfoChildEffectsChildEffect {
    
    private string nameField;
    
    private string triggerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string trigger {
        get {
            return this.triggerField;
        }
        set {
            this.triggerField = value;
        }
    }
}
